### ISSUE TITLE
Output flag sensitive to trailing separator

### ISSUE THREAD

**Issue by joshuata** [sosy-lab/sv-witnesses#2]
The script witness_validation_web_cloud.py requires a trailing slash for the output flag:
```
$ ./witness_validation_web_cloud.py --output output --program test-harnesses/example-1.i --witness test-harnesses/example-1-witness.graphml

...
2016-12-06 11:04:00,700 - INFO - Log file is written to outputoutput.log.
```

Additionally, if the directory does not exist the script fails:
```
$ ./witness_validation_web_cloud.py --output output/ --program test-harnesses/example-1.i --witness test-harnesses/example-1-witness.graphml

...
2016-12-06 10:57:27,289 - WARNING - Error while writing results of run test-harnesses/example-1-witness.graphml: [Errno 2] No such file or directory: 'output/output.log'
```

**Comment by PhilippWendler** [comment]
The first behavior is more or less intentional to allow adding arbitrary prefixes to file names in BenchExec, though I am not sure whether it is a good idea (especially for this script it probably makes no sense at all).

Failing on a missing directory is a bug.

**Comment by joshuata** [comment]
The reason I mentioned the first as a bug is that the behavior is somewhat inconsistent:
`./witness_validation_web_cloud.py --output output --program test-harnesses/example-1.i --witness test-harnesses/example-1-witness.graphml` creates a directory `output` and puts all the files in it except for output.log. I would expect that it would either prefix all filenames with the specified value or create the directory rather than a combination of the two depending on the file.

**Comment by PhilippWendler** [comment]
`output.log` is in the directory `output` because it is conceptually different from the files there: the directory contains files that were created by CPAchecker, `output.log` is stdout+stderr.

Though I would suggest to rename `output` to `output.files`, such that we have `output.log` and `output.files` (or with different names but same suffixes) if `--output` is used. This is also what BenchExec does.

**Comment by PhilippWendler** [comment]
Actually, sorry, BenchExec does not do it this way, it has different parameters `--output` and `--output-directory`, and it does not append any suffixes automatically. This would also be a possibility.
