### ISSUE TITLE
Attributes on graphml element

### ISSUE THREAD

**Issue by maul-esel** [sosy-lab/sv-witnesses#21]
The witnesses generated by Ultimate are currently rejected by the linter, with this warning:

https://github.com/sosy-lab/sv-witnesses/blob/e417bb6e94d82c7506aaf0a78c22a8263b9c6b4b/lint/witnesslint/linter.py#L723-L727

In our case, this is triggered by the attribute `xsi:schemaLocation`. While the witness specification seems not to mention anything about attributes on the `graphml` element (neither requiring nor disallowing them), the [GraphML Primer](http://graphml.graphdrawing.org/primer/graphml-primer.html), Section 2.2, mentions this attribute and says:
>  The XML Schema reference is not required but it provides means to validate the document and is therefore strongly recommended. 

So it seems to me the linter is too strict here. Though I'm not sure what the correct solution is – allow only this attribute? allow any attributes from other namespaces? sth else?

Cheers
Dominik

**Comment by MartinSpiessl** [comment]
Thanks for raising this issue!
Sounds like allowing/whitelisting the `xsi:schemaLocation` is the way to go here. @SvenUmbricht do you agree?

@maul-esel would that be an acceptable solution for you? If so could you provide a PR for the linter that does exactly that? And maybe provide a small witness(+program) from Ultimate that shows of this case, such that we can build test cases for the linter to avoid regression.

**Comment by SvenUmbricht** [comment]
I agree, `xsi:schemaLocation` should be allowed. I would suggest to only allow this attribute for now, and only whitelist others once there's a valid reason to do so.
It's probably acceptable to leave the value of this attribute unchecked, though it would make sense to at least make sure that the given namespace matches the one defined in the `xmlns` attribute.

**Comment by maul-esel** [comment]
Acceptable to me. I will provide a fix & test case after dinner.
