### ISSUE TITLE
Let WitnessLint output the type of the witness

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/sv-witnesses#55]
I would like to request the following feature:

The witness linter should show the type of the witness in the status.

This requires changes in the witness linter (log the content of the key `witness-type` in GramphML to stdout)
and in the tool-info module (instead of `return result.RESULT_DONE` change to `return result.RESULT_DONE + f" ({witness_type})" where `witness_type` is matched from the log output.

Optional (but this is neither urgent nor currently necessary):
The log output of WitnessLint could also include some more information that might be interesing for the users,
for example:
```
    "architecture": "32bit",
    "creationtime": "2021-12-06T14:44:55+01:00",
    "inputwitnesshash": "b74b9a4b98de1e383e38d91e28c3cfeed8d8428c9b166772b4a6f5288a75207f",
    "producer": "CPAchecker 2.1 / witnessValidation",
    "program-sha256": "77d80771821c1cd45088b62d9d16474928a377618be5caefce4c7c3ebfdda084",
    "programfile": "../../sv-benchmarks/c/seq-mthreaded/pals_STARTPALS_Triplicated.2.ufo.BOUNDED-10.pals.c",
    "programhash": "77d80771821c1cd45088b62d9d16474928a377618be5caefce4c7c3ebfdda084",
    "sourcecodelang": "C",
    "specification": "CHECK( init(main()), LTL(G ! call(reach_error())) )",
    "witness-file": "fileByHash/0a526b3e99025c41428566c92586c3c0c4c2e3dfc875bf9fa96cfc2bcfa29995.graphml",
    "witness-sha256": "0a526b3e99025c41428566c92586c3c0c4c2e3dfc875bf9fa96cfc2bcfa29995",
    "witness-size": 213910,
    "witness-type": "violation_witness"
 ```

**Comment by PhilippWendler** [comment]
The tool-info module could even provide the possibility to extract other metadata from the witness, even a generic feature such that you can ask for any [key that is present at top level in the witness](https://github.com/sosy-lab/sv-witnesses/blob/main/README-GraphML.md#graph-data-for-witness-automata) would be easy to implement, I guess.

**Comment by dbeyer** [comment]
First part implemented in https://github.com/sosy-lab/sv-witnesses/pull/56.
