### ISSUE TITLE
Example of a concurrency witness

### ISSUE THREAD

**Issue by peterschrammel** [sosy-lab/sv-witnesses#9]
A working example of a concurrency witness should be given. This would help reverse engineering the assumptions that the witness checker is making.

**Comment by kfriedberger** [comment]
Have you seen the example?
-> https://github.com/sosy-lab/sv-witnesses/blob/master/lazy01_false-unreach-call.i.graphml

**Comment by peterschrammel** [comment]
Thanks.  Maybe move it into a separate folder as done for the termination witnesses to make it easier to find.
